"""alert_monitor.py 在雲端主機(例如 fly.io)上執行時使用的設定來源——跟 alert_config.py
接口完全一樣(同樣的變數名),差別只在密鑰不是寫死在檔案裡,而是從環境變數讀。這個檔案
本身不含任何密鑰,可以放心進版控。

部署到 fly.io 時,用 `fly secrets set TELEGRAM_BOT_TOKEN=... TELEGRAM_CHAT_ID=...` 設定
這兩個環境變數(fly secrets 不會出現在程式碼或 log 裡)。WATCH_LIST 不是密鑰,直接寫死
在這裡就好,要改監控標的就直接改這個檔案、`fly deploy` 重新部署即可。

想暫停/恢復推播:改用 `fly secrets set ALERT_ENABLED=false` 再 `fly deploy`(雲端主機
沒辦法像本機那樣直接編輯檔案讓程式馬上偵測到,一定要重新部署才會生效——這跟本機執行
alert_monitor.py 時,改 alert_config.py 就能在30秒內自動生效的行為不一樣)。
"""

import os

TELEGRAM_BOT_TOKEN = os.environ["TELEGRAM_BOT_TOKEN"]
TELEGRAM_CHAT_ID = os.environ["TELEGRAM_CHAT_ID"]
ALERT_ENABLED = os.environ.get("ALERT_ENABLED", "true").lower() != "false"

# 下面股票清單是從使用者的 xq_branch_data/249.dsl(XQ全球贏家匯出的自選股)整批匯入,
# 用 xq_watchlist.read_watchlist_codes() 解析代號、fetch_data.get_chinese_name() 查中文
# 簡稱自動產生(2026-09-19)。alert_monitor.py改用批次查詢(intraday.get_intraday_quotes_batch)
# 之後,監控這個規模的清單不會拖慢輪詢間隔,詳見該函式的說明。
#
# 「自選要監控哪幾檔」:直接刪掉/註解掉不想監控的那幾行就好(前面加#),存檔後
# 記得 `fly deploy` 重新部署才會生效(見上面說明,雲端主機沒辦法像本機那樣自動偵測)。
# 兩個指數(櫃買/加權)建議保留,個股部分依你自己的需求增減。
#
# 249.dsl原本有247檔個股,其中2888/5371這兩檔查不到中文名稱、TWSE即時報價也抓不到
# (很可能是舊清單裡已經下市/併購/代號變更的股票),已經先拿掉不放進清單,不然每一輪
# 都會印「資料暫時無法取得」但永遠不會有資料。
WATCH_LIST = [
    {"label": "櫃買指數", "code": "o00", "otc": True},
    {"label": "加權指數", "code": "t00", "otc": False},
    {"label": "富邦上証", "code": "006205", "otc": False},
    {"label": "元大上證50", "code": "006206", "otc": False},
    {"label": "富邦深100", "code": "00639", "otc": False},
    {"label": "群益深証中小", "code": "00643", "otc": False},
    {"label": "元大台灣50", "code": "0050", "otc": False},
    {"label": "元大高股息", "code": "0056", "otc": False},
    {"label": "統一FANG+", "code": "00757", "otc": False},
    {"label": "國泰永續高股息", "code": "00878", "otc": False},
    {"label": "富邦越南", "code": "00885", "otc": False},
    {"label": "國泰智能電動車", "code": "00893", "otc": False},
    {"label": "群益台灣精選高息", "code": "00919", "otc": False},
    {"label": "群益台ESG低碳50", "code": "00923", "otc": False},
    {"label": "復華台灣科技優息", "code": "00929", "otc": False},
    {"label": "元大台灣價值高息", "code": "00940", "otc": False},
    {"label": "台泥", "code": "1101", "otc": False},
    {"label": "亞泥", "code": "1102", "otc": False},
    {"label": "大成", "code": "1210", "otc": False},
    {"label": "台塑", "code": "1301", "otc": False},
    {"label": "南亞", "code": "1303", "otc": False},
    {"label": "國喬", "code": "1312", "otc": False},
    {"label": "中石化", "code": "1314", "otc": False},
    {"label": "東陽", "code": "1319", "otc": False},
    {"label": "台化", "code": "1326", "otc": False},
    {"label": "遠東新", "code": "1402", "otc": False},
    {"label": "南紡", "code": "1440", "otc": False},
    {"label": "儒鴻", "code": "1476", "otc": False},
    {"label": "聚陽", "code": "1477", "otc": False},
    {"label": "士電", "code": "1503", "otc": False},
    {"label": "東元", "code": "1504", "otc": False},
    {"label": "中興電", "code": "1513", "otc": False},
    {"label": "和大", "code": "1536", "otc": False},
    {"label": "精華", "code": "1565", "otc": True},
    {"label": "亞德客-KY", "code": "1590", "otc": False},
    {"label": "華新", "code": "1605", "otc": False},
    {"label": "葡萄王", "code": "1707", "otc": False},
    {"label": "長興", "code": "1717", "otc": False},
    {"label": "中纖", "code": "1718", "otc": False},
    {"label": "台肥", "code": "1722", "otc": False},
    {"label": "美時", "code": "1795", "otc": False},
    {"label": "台玻", "code": "1802", "otc": False},
    {"label": "正隆", "code": "1904", "otc": False},
    {"label": "華紙", "code": "1905", "otc": False},
    {"label": "永豐餘", "code": "1907", "otc": False},
    {"label": "榮成", "code": "1909", "otc": False},
    {"label": "中鋼", "code": "2002", "otc": False},
    {"label": "東和鋼鐵", "code": "2006", "otc": False},
    {"label": "中鴻", "code": "2014", "otc": False},
    {"label": "大成鋼", "code": "2027", "otc": False},
    {"label": "上銀", "code": "2049", "otc": False},
    {"label": "正新", "code": "2105", "otc": False},
    {"label": "裕隆", "code": "2201", "otc": False},
    {"label": "為升", "code": "2231", "otc": False},
    {"label": "光寶科", "code": "2301", "otc": False},
    {"label": "聯電", "code": "2303", "otc": False},
    {"label": "台達電", "code": "2308", "otc": False},
    {"label": "金寶", "code": "2312", "otc": False},
    {"label": "華通", "code": "2313", "otc": False},
    {"label": "鴻海", "code": "2317", "otc": False},
    {"label": "中環", "code": "2323", "otc": False},
    {"label": "仁寶", "code": "2324", "otc": False},
    {"label": "國巨*", "code": "2327", "otc": False},
    {"label": "廣宇", "code": "2328", "otc": False},
    {"label": "台積電", "code": "2330", "otc": False},
    {"label": "精英", "code": "2331", "otc": False},
    {"label": "友訊", "code": "2332", "otc": False},
    {"label": "旺宏", "code": "2337", "otc": False},
    {"label": "光罩", "code": "2338", "otc": False},
    {"label": "台亞", "code": "2340", "otc": False},
    {"label": "華邦電", "code": "2344", "otc": False},
    {"label": "智邦", "code": "2345", "otc": False},
    {"label": "聯強", "code": "2347", "otc": False},
    {"label": "佳世達", "code": "2352", "otc": False},
    {"label": "宏碁", "code": "2353", "otc": False},
    {"label": "鴻準", "code": "2354", "otc": False},
    {"label": "敬鵬", "code": "2355", "otc": False},
    {"label": "英業達", "code": "2356", "otc": False},
    {"label": "華碩", "code": "2357", "otc": False},
    {"label": "致茂", "code": "2360", "otc": False},
    {"label": "大同", "code": "2371", "otc": False},
    {"label": "技嘉", "code": "2376", "otc": False},
    {"label": "微星", "code": "2377", "otc": False},
    {"label": "瑞昱", "code": "2379", "otc": False},
    {"label": "廣達", "code": "2382", "otc": False},
    {"label": "台光電", "code": "2383", "otc": False},
    {"label": "群光", "code": "2385", "otc": False},
    {"label": "威盛", "code": "2388", "otc": False},
    {"label": "正崴", "code": "2392", "otc": False},
    {"label": "億光", "code": "2393", "otc": False},
    {"label": "凌陽", "code": "2401", "otc": False},
    {"label": "漢唐", "code": "2404", "otc": False},
    {"label": "南亞科", "code": "2408", "otc": False},
    {"label": "友達", "code": "2409", "otc": False},
    {"label": "中華電", "code": "2412", "otc": False},
    {"label": "美律", "code": "2439", "otc": False},
    {"label": "超豐", "code": "2441", "otc": False},
    {"label": "京元電子", "code": "2449", "otc": False},
    {"label": "全新", "code": "2455", "otc": False},
    {"label": "飛宏", "code": "2457", "otc": False},
    {"label": "義隆", "code": "2458", "otc": False},
    {"label": "可成", "code": "2474", "otc": False},
    {"label": "強茂", "code": "2481", "otc": False},
    {"label": "兆赫", "code": "2485", "otc": False},
    {"label": "一詮", "code": "2486", "otc": False},
    {"label": "瑞軒", "code": "2489", "otc": False},
    {"label": "華新科", "code": "2492", "otc": False},
    {"label": "宏達電", "code": "2498", "otc": False},
    {"label": "中工", "code": "2515", "otc": False},
    {"label": "冠德", "code": "2520", "otc": False},
    {"label": "興富發", "code": "2542", "otc": False},
    {"label": "華固", "code": "2548", "otc": False},
    {"label": "長榮", "code": "2603", "otc": False},
    {"label": "新興", "code": "2605", "otc": False},
    {"label": "裕民", "code": "2606", "otc": False},
    {"label": "陽明", "code": "2609", "otc": False},
    {"label": "華航", "code": "2610", "otc": False},
    {"label": "萬海", "code": "2615", "otc": False},
    {"label": "長榮航", "code": "2618", "otc": False},
    {"label": "台灣高鐵", "code": "2633", "otc": False},
    {"label": "漢翔", "code": "2634", "otc": False},
    {"label": "彰銀", "code": "2801", "otc": False},
    {"label": "臺企銀", "code": "2834", "otc": False},
    {"label": "華南金", "code": "2880", "otc": False},
    {"label": "富邦金", "code": "2881", "otc": False},
    {"label": "國泰金", "code": "2882", "otc": False},
    {"label": "凱基金", "code": "2883", "otc": False},
    {"label": "玉山金", "code": "2884", "otc": False},
    {"label": "元大金", "code": "2885", "otc": False},
    {"label": "兆豐金", "code": "2886", "otc": False},
    {"label": "台新新光金", "code": "2887", "otc": False},
    {"label": "中信金", "code": "2891", "otc": False},
    {"label": "第一金", "code": "2892", "otc": False},
    {"label": "農林", "code": "2913", "otc": False},
    {"label": "潤泰全", "code": "2915", "otc": False},
    {"label": "神基", "code": "3005", "otc": False},
    {"label": "晶豪科", "code": "3006", "otc": False},
    {"label": "大立光", "code": "3008", "otc": False},
    {"label": "奇鋐", "code": "3017", "otc": False},
    {"label": "亞光", "code": "3019", "otc": False},
    {"label": "聯詠", "code": "3034", "otc": False},
    {"label": "智原", "code": "3035", "otc": False},
    {"label": "文曄", "code": "3036", "otc": False},
    {"label": "欣興", "code": "3037", "otc": False},
    {"label": "晶技", "code": "3042", "otc": False},
    {"label": "台灣大", "code": "3045", "otc": False},
    {"label": "僑威", "code": "3078", "otc": True},
    {"label": "聯亞", "code": "3081", "otc": True},
    {"label": "穩懋", "code": "3105", "otc": True},
    {"label": "璟德", "code": "3152", "otc": True},
    {"label": "景碩", "code": "3189", "otc": False},
    {"label": "原相", "code": "3227", "otc": True},
    {"label": "緯創", "code": "3231", "otc": False},
    {"label": "威剛", "code": "3260", "otc": True},
    {"label": "欣銓", "code": "3264", "otc": True},
    {"label": "鈊象", "code": "3293", "otc": True},
    {"label": "雙鴻", "code": "3324", "otc": True},
    {"label": "新日興", "code": "3376", "otc": False},
    {"label": "明泰", "code": "3380", "otc": False},
    {"label": "玉晶光", "code": "3406", "otc": False},
    {"label": "創意", "code": "3443", "otc": False},
    {"label": "群創", "code": "3481", "otc": False},
    {"label": "力旺", "code": "3529", "otc": True},
    {"label": "台勝科", "code": "3532", "otc": False},
    {"label": "嘉澤", "code": "3533", "otc": False},
    {"label": "同致", "code": "3552", "otc": True},
    {"label": "健策", "code": "3653", "otc": False},
    {"label": "TPK-KY", "code": "3673", "otc": False},
    {"label": "家登", "code": "3680", "otc": True},
    {"label": "碩禾", "code": "3691", "otc": True},
    {"label": "大聯大", "code": "3702", "otc": False},
    {"label": "神達", "code": "3706", "otc": False},
    {"label": "日月光投控", "code": "3711", "otc": False},
    {"label": "富采", "code": "3714", "otc": False},
    {"label": "晟德", "code": "4123", "otc": True},
    {"label": "中天", "code": "4128", "otc": True},
    {"label": "智擎", "code": "4162", "otc": True},
    {"label": "泰博", "code": "4736", "otc": False},
    {"label": "合一", "code": "4743", "otc": True},
    {"label": "遠傳", "code": "4904", "otc": False},
    {"label": "新唐", "code": "4919", "otc": False},
    {"label": "和碩", "code": "4938", "otc": False},
    {"label": "臻鼎-KY", "code": "4958", "otc": False},
    {"label": "榮剛", "code": "5009", "otc": True},
    {"label": "亞昕", "code": "5213", "otc": True},
    {"label": "祥碩", "code": "5269", "otc": False},
    {"label": "信驊", "code": "5274", "otc": True},
    {"label": "世界", "code": "5347", "otc": True},
    {"label": "中磊", "code": "5388", "otc": False},
    {"label": "台半", "code": "5425", "otc": True},
    {"label": "宣德", "code": "5457", "otc": True},
    {"label": "中美晶", "code": "5483", "otc": True},
    {"label": "長虹", "code": "5534", "otc": False},
    {"label": "中租-KY", "code": "5871", "otc": False},
    {"label": "上海商銀", "code": "5876", "otc": False},
    {"label": "合庫金", "code": "5880", "otc": False},
    {"label": "寶雅*", "code": "5904", "otc": True},
    {"label": "群益證", "code": "6005", "otc": False},
    {"label": "彩晶", "code": "6116", "otc": False},
    {"label": "新普", "code": "6121", "otc": True},
    {"label": "亞翔", "code": "6139", "otc": False},
    {"label": "頎邦", "code": "6147", "otc": True},
    {"label": "嘉聯益", "code": "6153", "otc": False},
    {"label": "信昌電", "code": "6173", "otc": True},
    {"label": "瑞儀", "code": "6176", "otc": False},
    {"label": "合晶", "code": "6182", "otc": True},
    {"label": "廣明", "code": "6188", "otc": True},
    {"label": "旺矽", "code": "6223", "otc": True},
    {"label": "力成", "code": "6239", "otc": False},
    {"label": "立端", "code": "6245", "otc": True},
    {"label": "矽格", "code": "6257", "otc": False},
    {"label": "台郡", "code": "6269", "otc": False},
    {"label": "同欣電", "code": "6271", "otc": False},
    {"label": "台燿", "code": "6274", "otc": True},
    {"label": "台表科", "code": "6278", "otc": False},
    {"label": "康舒", "code": "6282", "otc": False},
    {"label": "啟碁", "code": "6285", "otc": False},
    {"label": "樺漢", "code": "6414", "otc": False},
    {"label": "元晶", "code": "6443", "otc": False},
    {"label": "保瑞", "code": "6472", "otc": False},
    {"label": "環球晶", "code": "6488", "otc": True},
    {"label": "台塑化", "code": "6505", "otc": False},
    {"label": "精測", "code": "6510", "otc": True},
    {"label": "達發", "code": "6526", "otc": False},
    {"label": "高端疫苗", "code": "6547", "otc": True},
    {"label": "緯穎", "code": "6669", "otc": False},
    {"label": "台灣虎航", "code": "6757", "otc": False},
    {"label": "力積電", "code": "6770", "otc": False},
    {"label": "台虹", "code": "8039", "otc": False},
    {"label": "網家", "code": "8044", "otc": True},
    {"label": "南電", "code": "8046", "otc": False},
    {"label": "元太", "code": "8069", "otc": True},
    {"label": "宏捷科", "code": "8086", "otc": True},
    {"label": "至上", "code": "8112", "otc": False},
    {"label": "南茂", "code": "8150", "otc": False},
    {"label": "達方", "code": "8163", "otc": False},
    {"label": "群聯", "code": "8299", "otc": True},
    {"label": "金居", "code": "8358", "otc": True},
    {"label": "大江", "code": "8436", "otc": True},
    {"label": "富邦媒", "code": "8454", "otc": False},
    {"label": "寶成", "code": "9904", "otc": False},
    {"label": "美利達", "code": "9914", "otc": False},
    {"label": "百和", "code": "9938", "otc": False},
    {"label": "宏全", "code": "9939", "otc": False},
    {"label": "潤泰新", "code": "9945", "otc": False},
    {"label": "世紀鋼", "code": "9958", "otc": False},
    {"label": "胡連", "code": "6279", "otc": True},
]
